"""Variant directory scanner + __init__.py regenerator (REG-02 / D-29)."""
from __future__ import annotations

import importlib.util
import logging
import os
import sys
import tempfile
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class ScanResult:
    """Outcome of scan_variants(variants_root).

    `imported` is the list of variant module paths whose import succeeded
    (and thus whose @register decorator ran).

    `failed` is the list of (path, exception_str) tuples for modules whose
    import raised. Plan 01-09 (refresh-registry) decides whether to fail
    (--strict) or warn-and-continue based on this list.

    `skipped` is the list of paths the scanner intentionally skipped
    (`__init__.py`, `_*.py` other than the kind subdirs themselves).
    """
    imported: tuple[Path, ...] = field(default_factory=tuple)
    failed: tuple[tuple[Path, str], ...] = field(default_factory=tuple)
    skipped: tuple[Path, ...] = field(default_factory=tuple)


def _is_variant_module(path: Path) -> bool:
    """Return True when path is a variant module (excludes __init__.py and _*.py helpers)."""
    if path.suffix != ".py":
        return False
    if path.name == "__init__.py":
        return False
    if path.name.startswith("_"):
        return False
    return True


def _import_path(path: Path) -> None:
    """Import a single .py file by absolute path.

    Uses a unique module name per file path so re-scans don't pollute
    sys.modules with conflicting short names.  Two files at
    ``variants/a/b.py`` and ``variants/c/b.py`` each get a distinct key.
    """
    # Stable module name: encode the absolute posix path into a valid identifier.
    safe = path.as_posix().replace("/", "_").replace(".", "_").replace("-", "_")
    module_name = f"_automil_variant_{safe}"

    spec = importlib.util.spec_from_file_location(module_name, path)
    if spec is None or spec.loader is None:
        raise ImportError(f"cannot create module spec for {path}")
    module = importlib.util.module_from_spec(spec)
    # Register before exec so relative imports within the module resolve.
    sys.modules[module_name] = module
    try:
        spec.loader.exec_module(module)  # type: ignore[union-attr]
    except Exception:
        sys.modules.pop(module_name, None)
        raise


def scan_variants(variants_root: Path) -> ScanResult:
    """Walk variants_root and import every variant module.

    Discovery rules (D-29):
      - Each immediate subdirectory of variants_root is either a parent name
        ('clam_mb', 'ab_mil') OR one of '_losses' / '_policies' / '_candidates'.
      - Inside each subdir, every `*.py` file (other than `__init__.py` and
        any `_<name>.py` "private helper" files) is imported.
      - The scanner does NOT clear the registry beforehand; callers (Plan 01-09)
        call `_clear_registry()` first if they want a fresh start.

    Returns a ScanResult capturing imported / failed / skipped paths.

    Importing a module that contains `@register(VariantSpec(...))` triggers
    Plan 01-02's decorator, which validates the spec and inserts into the
    singleton dicts. A duplicate-name error from @register surfaces here as
    a failed-import entry.
    """
    if not variants_root.exists():
        return ScanResult()

    imported: list[Path] = []
    failed: list[tuple[Path, str]] = []
    skipped: list[Path] = []

    for sub in sorted(variants_root.iterdir()):
        if not sub.is_dir():
            continue
        for py_file in sorted(sub.iterdir()):
            if py_file.is_dir():
                # No nested variant dirs in Phase 1; skip silently.
                continue
            if not _is_variant_module(py_file):
                if py_file.suffix == ".py":
                    skipped.append(py_file)
                continue
            try:
                _import_path(py_file)
                imported.append(py_file)
            except Exception as exc:
                failed.append((py_file, f"{type(exc).__name__}: {exc}"))
                logger.warning("Failed to import variant module %s: %s", py_file, exc)

    return ScanResult(
        imported=tuple(imported),
        failed=tuple(failed),
        skipped=tuple(skipped),
    )


def regenerate_init_py(kind_dir: Path) -> str:
    """Regenerate `<kind_dir>/__init__.py` with imports-only manifest (D-29).

    The output looks like::

        # AUTO-GENERATED by `automil refresh-registry`. DO NOT EDIT.
        # Re-run the command after adding or renaming a variant module.
        # generated-at: 2026-05-02T10:00:00.000000+00:00
        from . import clam_mb_v0176  # noqa: F401
        from . import clam_mb_v0188  # noqa: F401

    Deterministic ordering: alphabetic on ``module_name``.

    Idempotent: the timestamp is on a *separate* ``# generated-at:`` comment
    line.  Stripping that one line produces byte-identical content across
    consecutive runs when directory contents have not changed.

    Returns the rendered content as a string AND writes it atomically to disk.
    """
    if not kind_dir.exists():
        kind_dir.mkdir(parents=True, exist_ok=True)

    # Discover variant modules in alphabetic order (skip __init__ and _*.py).
    modules: list[str] = []
    for py_file in sorted(kind_dir.iterdir()):
        if py_file.is_file() and _is_variant_module(py_file):
            modules.append(py_file.stem)

    # Timestamp on a SEPARATE line so the body bytes are stable across runs.
    ts = datetime.now(tz=timezone.utc).isoformat()
    header = (
        "# AUTO-GENERATED by `automil refresh-registry`. DO NOT EDIT.\n"
        "# Re-run the command after adding or renaming a variant module.\n"
        f"# generated-at: {ts}\n"
    )
    if modules:
        body = "\n".join(f"from . import {m}  # noqa: F401" for m in modules) + "\n"
    else:
        body = ""
    rendered = header + body

    # Atomic write (PATTERNS.md §3 — tempfile on same filesystem, then os.rename).
    target = kind_dir / "__init__.py"
    tmp_fd, tmp_path = tempfile.mkstemp(dir=str(kind_dir), suffix=".tmp")
    try:
        with os.fdopen(tmp_fd, "w") as f:
            f.write(rendered)
        os.rename(tmp_path, str(target))
        os.utime(str(target))
    except Exception:
        if os.path.exists(tmp_path):
            os.unlink(tmp_path)
        raise

    logger.info("Regenerated %s (%d imports)", target, len(modules))
    return rendered
