"""PHASE 1 ACCEPTANCE GATE: synthetic-consumer end-to-end round-trip (D-50).

These tests validate the complete framework registry pipeline via the REAL
CLI commands — port-variant -> apply -> verify-repro — with NO mock injection
of variant_spec into graph.json (BLOCKER-02 contract from Plan 01-11).

If `test_full_roundtrip_passes` passes, Phase 1 is done.
"""
from __future__ import annotations

import json
import re
import shutil
import subprocess
from pathlib import Path

import pytest
import yaml
from click.testing import CliRunner


# Deterministic body that the test injects AFTER port-variant produces its
# NotImplementedError stub (D-37: byte-identical port is consumer follow-up;
# the test plays operator and pastes a deterministic forward).
DETERMINISTIC_FORWARD_BODY = """    def forward(self, features=None, coords=None):
        # Deterministic synthetic composite tuned to mid-band of the default
        # tolerance (0.005). Returns 0.502 regardless of input.
        return 0.502
"""


def _init_git_repo(path: Path):
    path.mkdir(parents=True, exist_ok=True)
    subprocess.run(["git", "init"], cwd=path, capture_output=True, check=True)
    subprocess.run(["git", "config", "user.name", "test"], cwd=path, capture_output=True)
    subprocess.run(
        ["git", "config", "user.email", "test@test.com"], cwd=path, capture_output=True
    )


def _copy_fixture(tmp_path: Path):
    fixture_src = Path(__file__).parent / "fixtures" / "synthetic_consumer"
    for item in fixture_src.iterdir():
        dst = tmp_path / item.name
        if item.is_dir():
            shutil.copytree(item, dst)
        elif item.is_file() and item.name != "__init__.py":
            shutil.copy2(item, dst)


def _setup(tmp_path: Path) -> tuple[Path, Path, str]:
    _copy_fixture(tmp_path)
    _init_git_repo(tmp_path)
    subprocess.run(["git", "add", "."], cwd=tmp_path, capture_output=True, check=True)
    subprocess.run(
        ["git", "commit", "-m", "initial"], cwd=tmp_path, capture_output=True, check=True
    )
    head = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=tmp_path,
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip()
    return tmp_path, tmp_path / "automil", head


def _write_archive_spec(
    adir: Path,
    node_id: str,
    *,
    overlay: dict,
    parent: str | None,
    base_commit: str,
    composite: float = 0.502,
):
    """Simulate `automil submit` having written archive/<node_id>/spec.json."""
    archive = adir / "orchestrator" / "archive" / node_id
    archive.mkdir(parents=True, exist_ok=True)
    spec = {
        "id": node_id,
        "base_commit": base_commit,
        "overlay_manifest": overlay,
        "deletions": [],
        "composite": composite,
        "graph_metadata": {"parent_id": parent, "techniques": []},
    }
    (archive / "spec.json").write_text(json.dumps(spec, indent=2))


def _write_graph_node_no_variant_spec(
    adir: Path, node_id: str, *, composite: float, base_commit: str
):
    """Realistic state after `automil submit` but BEFORE port-variant:
    the node exists, but variant_spec is NOT populated. port-variant's job
    is to add variant_spec (BLOCKER-02 contract from Plan 01-11)."""
    graph = {
        "schema_version": 1,
        "meta": {
            "best_node_id": node_id,
            "best_composite": composite,
            "total_executed": 1,
            "total_proposed": 0,
            "next_id": 2,
            "baseline_composite": 0.5,
            "scoring": {"exploration_weight": 0.005, "novelty_weight": 0.003},
        },
        "nodes": {
            node_id: {
                "id": node_id,
                "type": "executed",
                "status": "keep",
                "composite": composite,
                "base_commit": base_commit,
                "created_at": "2026-05-02T10:00:00Z",
                # NO variant_spec — port-variant adds it.
            },
        },
        "technique_stats": {},
    }
    (adir / "graph.json").write_text(json.dumps(graph, indent=2))


def _swap_stub_forward_with_deterministic(module_path: Path) -> None:
    """port-variant's stub raises NotImplementedError per D-37. The test plays
    the role of operator and pastes a deterministic forward body. Class shape,
    @register, ABC subclass, and the docstring header are preserved."""
    text = module_path.read_text()
    # Replace the entire `def forward(...)` block with the deterministic body.
    # The stub generated by port-variant has shape:
    #   def forward(self, features, coords=None):
    #       # TODO: paste the variant's forward body here.
    #       # See sources: ...
    #       raise NotImplementedError("variant body not yet ported")
    new_text = re.sub(
        r"    def forward\(self, features, coords=None\):\n(?:        .*\n)+",
        DETERMINISTIC_FORWARD_BODY,
        text,
        count=1,
    )
    if new_text == text:
        raise RuntimeError(
            "Failed to swap stub forward body — port-variant's output shape may have drifted. "
            "Inspect %s and update _swap_stub_forward_with_deterministic." % module_path
        )
    module_path.write_text(new_text)


@pytest.fixture
def cli_runner():
    return CliRunner()


@pytest.fixture(autouse=True)
def _isolated_registry():
    from automil.registry._state import _clear_registry

    _clear_registry()
    yield
    _clear_registry()


def test_full_roundtrip_passes(tmp_path, cli_runner, monkeypatch):
    """PHASE 1 ACCEPTANCE GATE — REAL CLI pipeline, NO mock injection.

    Pipeline:
      (a) simulate `automil submit` by writing archive/<node_id>/spec.json + graph.json node
      (b) `automil port-variant <node_id>` writes variant module + manifest +
          MUTATES graph.json to add `node['variant_spec']` (BLOCKER-02 contract)
      (c) test plays operator (D-37): swap port-variant's NotImplementedError
          stub with a deterministic 0.502 forward
      (d) `automil refresh-registry` picks up the new body
      (e) `automil apply <node_id>` reads `node['variant_spec']` from REAL graph.json
          (no test scaffolding) -> writes config.yaml
      (f) `automil verify-repro <node_id>` reproduces -> pass manifest

    If this test passes, Phase 1 ships AND the BLOCKER-02 lifecycle integration
    is operationally exercised end-to-end.
    """
    proj, adir, head = _setup(tmp_path)
    monkeypatch.chdir(proj)

    # (a) Simulate submit. The overlay touches a model-like path so port-variant
    # auto-detects kind=model; parent comes from graph_metadata.parent_id.
    node_id = "node_0001"
    _write_archive_spec(
        adir,
        node_id,
        overlay={"variants/synthstub/baseline.py": "sha:..."},
        parent="synthstub",
        base_commit=head,
        composite=0.502,
    )
    _write_graph_node_no_variant_spec(adir, node_id, composite=0.502, base_commit=head)

    from automil.cli import main

    # (b) port-variant — writes variant module body + manifest + graph.json mutation.
    port = cli_runner.invoke(
        main,
        ["port-variant", node_id, "--kind", "model", "--parent", "synthstub"],
    )
    assert port.exit_code == 0, port.output

    # Sanity: port-variant honoured the BLOCKER-02 contract.
    graph = json.loads((adir / "graph.json").read_text())
    assert "variant_spec" in graph["nodes"][node_id], (
        "BLOCKER-02 regression: port-variant did not write variant_spec into graph.json. "
        "apply will hard-fail. See Plan 01-11 graph mutation step."
    )
    spec_in_graph = graph["nodes"][node_id]["variant_spec"]
    assert spec_in_graph["kind"] == "model"
    assert spec_in_graph["parent"] == "synthstub"
    variant_name = spec_in_graph["name"]  # e.g., "synthstub_v0001"

    module_path = adir / "variants" / "synthstub" / f"{variant_name}.py"
    manifest_path = adir / "variants" / "synthstub" / f"{variant_name}.json"
    assert module_path.exists()
    assert manifest_path.exists()

    # (c) Test plays operator — swap port-variant's stub for a deterministic body.
    _swap_stub_forward_with_deterministic(module_path)

    # (d) refresh-registry — picks up the new body.
    rr = cli_runner.invoke(main, ["refresh-registry"])
    assert rr.exit_code == 0, rr.output

    # (e) apply — reads variant_spec from the REAL graph.json (no mock).
    ap = cli_runner.invoke(main, ["apply", node_id])
    assert ap.exit_code == 0, ap.output
    cfg = yaml.safe_load((adir / "config.yaml").read_text())
    assert cfg["model"]["variant"] == variant_name
    assert cfg["model"]["parent"] == "synthstub"

    # Commit the worktree state so verify-repro's worktree (created at
    # base_commit) has the variant module + active config.
    subprocess.run(["git", "add", "."], cwd=proj, capture_output=True, check=True)
    subprocess.run(
        ["git", "commit", "-m", "port + apply node_0001"],
        cwd=proj,
        capture_output=True,
        check=True,
    )
    new_head = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=proj,
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip()
    # Update graph.json's base_commit to the post-port-and-apply HEAD.
    graph = json.loads((adir / "graph.json").read_text())
    graph["nodes"][node_id]["base_commit"] = new_head
    (adir / "graph.json").write_text(json.dumps(graph, indent=2))
    subprocess.run(
        ["git", "add", "automil/graph.json"], cwd=proj, capture_output=True, check=True
    )
    subprocess.run(
        ["git", "commit", "--amend", "--no-edit"], cwd=proj, capture_output=True, check=True
    )

    # (f) verify-repro.
    vr = cli_runner.invoke(main, ["verify-repro", node_id])
    assert vr.exit_code == 0, vr.output

    manifest = yaml.safe_load((adir / "repro_manifest.yaml").read_text())
    assert manifest["status"] == "pass"
    assert manifest["actual_composite"] == pytest.approx(0.502, abs=0.001)
    assert manifest["expected_composite"] == pytest.approx(0.502)
    assert manifest["tolerance"] == pytest.approx(0.005)


def test_full_roundtrip_fail_exceeds_tolerance(tmp_path, cli_runner, monkeypatch):
    """Same REAL pipeline but recorded composite drifts beyond tolerance."""
    proj, adir, head = _setup(tmp_path)
    monkeypatch.chdir(proj)

    node_id = "node_0001"
    _write_archive_spec(
        adir,
        node_id,
        overlay={"variants/synthstub/baseline.py": "sha:..."},
        parent="synthstub",
        base_commit=head,
        composite=0.700,  # archive thinks 0.700
    )
    _write_graph_node_no_variant_spec(adir, node_id, composite=0.700, base_commit=head)

    from automil.cli import main

    cli_runner.invoke(
        main, ["port-variant", node_id, "--kind", "model", "--parent", "synthstub"]
    )

    graph = json.loads((adir / "graph.json").read_text())
    variant_name = graph["nodes"][node_id]["variant_spec"]["name"]
    module_path = adir / "variants" / "synthstub" / f"{variant_name}.py"
    # Variant produces 0.502 but graph records 0.700 -> verify-repro should fail.
    _swap_stub_forward_with_deterministic(module_path)

    cli_runner.invoke(main, ["refresh-registry"])
    cli_runner.invoke(main, ["apply", node_id])

    subprocess.run(["git", "add", "."], cwd=proj, capture_output=True, check=True)
    subprocess.run(
        ["git", "commit", "-m", "port + apply"], cwd=proj, capture_output=True, check=True
    )
    new_head = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=proj,
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip()
    graph = json.loads((adir / "graph.json").read_text())
    graph["nodes"][node_id]["base_commit"] = new_head
    (adir / "graph.json").write_text(json.dumps(graph, indent=2))
    subprocess.run(
        ["git", "add", "automil/graph.json"], cwd=proj, capture_output=True, check=True
    )
    subprocess.run(
        ["git", "commit", "--amend", "--no-edit"], cwd=proj, capture_output=True, check=True
    )

    result = cli_runner.invoke(main, ["verify-repro", node_id])
    assert result.exit_code != 0  # fail
    manifest = yaml.safe_load((adir / "repro_manifest.yaml").read_text())
    assert manifest["status"] == "fail"
    assert manifest["actual_composite"] == pytest.approx(0.502)
    assert manifest["expected_composite"] == pytest.approx(0.700)


def test_port_variant_writes_variant_spec_to_graph_json(tmp_path, cli_runner, monkeypatch):
    """BLOCKER-02 regression-prevention test (top-level, distinct from the
    full round-trip). Asserts ONLY that port-variant populates
    `graph.json -> nodes[node_id] -> variant_spec`. If a future refactor
    removes Plan 01-11's graph mutation step, this test fires immediately.
    """
    proj, adir, head = _setup(tmp_path)
    monkeypatch.chdir(proj)

    node_id = "node_0042"
    _write_archive_spec(
        adir,
        node_id,
        overlay={"variants/synthstub/baseline.py": "sha:..."},
        parent="synthstub",
        base_commit=head,
        composite=0.5,
    )
    _write_graph_node_no_variant_spec(adir, node_id, composite=0.5, base_commit=head)

    from automil.cli import main

    result = cli_runner.invoke(
        main,
        ["port-variant", node_id, "--kind", "model", "--parent", "synthstub"],
    )
    assert result.exit_code == 0, result.output

    graph = json.loads((adir / "graph.json").read_text())
    assert "variant_spec" in graph["nodes"][node_id]
    spec = graph["nodes"][node_id]["variant_spec"]
    assert spec["kind"] == "model"
    assert spec["parent"] == "synthstub"
    assert spec["name"].startswith("synthstub_v")
